Added TAB shortcut to focus the chat textbox when it is not in focus.…
MemeLabs/chat-gui pull request #456
Opened 2021-06-20 04:38 UTC by ftwpala

… Added setting for max messages (extracted from command) and added a disable option for chat combos.

2021-06-20 12:26 UTC, jbpratt requested changes
my being nit-picky :smiley_cat:

2021-06-20 12:26 UTC, jbpratt commented on assets/chat/js/chat.js
> +            win.lastmessage.emotecount > 1
```suggestion
            win.lastmessage.emotecount > 1
```

2021-06-20 12:26 UTC, jbpratt commented on assets/chat/js/menus.js
> +        if(data ==""){
```suggestion
        if(data == ""){
```

2021-06-20 12:26 UTC, jbpratt commented on assets/chat/js/menus.js
> +            this.chat.commitSettings();
```suggestion
            this.chat.commitSettings();
```

2021-06-20 12:29 UTC, SoMuchForSubtlety approved these changes

2021-06-21 05:43 UTC, slugalisk approved these changes

2021-06-21 05:43 UTC, merged